export const ROUTES = {
  LOGIN: '/login',
  REGISTRATION: '/registration',
  FORGOT_PASSWORD: '/forgotPassword',
  LOCATION_CURRENT: '/location/[patientId]',
  PATIENT_REGISTRSTION: '/add-patient',
  REGISTER_DOCTOR: '/register-doctor',
  RESET_PASSWORD: '/resetPassword',
  PRIVACY_POLICY: '/privacyPolicy',
  ZOHOOAuthToken: '/zohoOauthToken',
  LEDGER:"/ledger"
};

export const PUBLIC_PATHS = [
  ROUTES.LOGIN,
  ROUTES.REGISTRATION,
  ROUTES.FORGOT_PASSWORD,
  ROUTES.LOCATION_CURRENT,
  ROUTES.PATIENT_REGISTRSTION,
  ROUTES.REGISTER_DOCTOR,
  ROUTES.RESET_PASSWORD,
  ROUTES.PRIVACY_POLICY,
  ROUTES.ZOHOOAuthToken,
];
export const REGISTRATION_PATHS = [ROUTES.REGISTRATION, ROUTES.PATIENT_REGISTRSTION, ROUTES.REGISTER_DOCTOR];
